name: Test

# Run this job on all pushes and pull requests
on:
    push:
        branches:
            - "**"
    pull_request: {}

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

env:
    CI: true

jobs:
    ci-tests:
        if: contains(github.event.head_commit.message, '[skip ci]') == false

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
            
              with:
                node-version: ${{ matrix.node-version }}

            - run: npm ci
            - run: npm ci-test